
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bambang
 */
public class KTP extends javax.swing.JFrame {

    /**
     * Creates new form KTP
     */
    public KTP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        NIK = new javax.swing.JTextField();
        NAMA = new javax.swing.JTextField();
        TTL = new javax.swing.JTextField();
        BERLAKU = new javax.swing.JTextField();
        ALAMAT = new javax.swing.JTextField();
        KECAMATAN = new javax.swing.JTextField();
        CETAK = new javax.swing.JButton();
        KELUAR = new javax.swing.JButton();
        KERJA = new javax.swing.JComboBox<>();
        AGAMA = new javax.swing.JComboBox<>();
        INA = new javax.swing.JRadioButton();
        ASING = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        LK = new javax.swing.JRadioButton();
        PR = new javax.swing.JRadioButton();
        RT = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        RW = new javax.swing.JTextField();
        STATUS = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        clear = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        HARI = new javax.swing.JComboBox<>();
        BULAN = new javax.swing.JComboBox<>();
        TAHUN = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField4.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("KARTU TANDA PENDUDUK");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 0, -1, -1));

        jLabel2.setText("NIK");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, -1, -1));

        jLabel3.setText("NAMA");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, -1, -1));

        jLabel4.setText("TTL");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 124, -1, -1));

        jLabel5.setText("Jenis Kelamin");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, -1, -1));

        jLabel6.setText("ALAMAT");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel7.setText("RT/RW");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel8.setText("Kecamatan");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel9.setText("AGAMA");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel10.setText("STATUS");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 331, -1, -1));

        jLabel11.setText("PEKERJAAN");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 367, -1, -1));

        jLabel12.setText("NEGARA");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 398, -1, -1));

        jLabel13.setText("DIBUAT");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 80, -1));

        jLabel16.setText(":");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 54, 10, -1));

        jLabel18.setText(":");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 89, 15, -1));

        jLabel19.setText(":");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 127, 18, -1));

        jLabel20.setText(":");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 203, 0, -1));

        jLabel21.setText(":");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 165, 16, -1));

        jLabel22.setText(":");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 234, -1, -1));

        jLabel23.setText(":");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 265, 10, 10));

        jLabel24.setText(":");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 334, 16, -1));

        jLabel25.setText(":");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 303, 16, -1));

        jLabel26.setText(":");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 362, 14, 25));

        jLabel27.setText(":");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 398, 14, -1));

        jLabel28.setText(":");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 10, 10));

        NIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIKActionPerformed(evt);
            }
        });
        jPanel2.add(NIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 238, -1));
        jPanel2.add(NAMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 86, 238, -1));

        TTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TTLActionPerformed(evt);
            }
        });
        jPanel2.add(TTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 124, 238, -1));
        jPanel2.add(BERLAKU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 236, -1));
        jPanel2.add(ALAMAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 236, -1));
        jPanel2.add(KECAMATAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 260, 242, -1));

        CETAK.setText("Cetak");
        CETAK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CETAKActionPerformed(evt);
            }
        });
        jPanel2.add(CETAK, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 492, -1, -1));

        KELUAR.setText("Keluar");
        KELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KELUARActionPerformed(evt);
            }
        });
        jPanel2.add(KELUAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 492, -1, -1));

        KERJA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Swasta", "Ibu Rumah Tangga", "PNS", "Abri/Polisi", "Buruh", "Guru", " " }));
        jPanel2.add(KERJA, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 364, -1, -1));

        AGAMA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Katolik", "Hindu", "Budha" }));
        jPanel2.add(AGAMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 300, -1, -1));

        buttonGroup2.add(INA);
        INA.setText("Indonesia");
        jPanel2.add(INA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, 30));

        buttonGroup2.add(ASING);
        ASING.setText("Asing");
        jPanel2.add(ASING, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 393, -1, 20));

        jLabel14.setText(":");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 203, 10, -1));

        buttonGroup3.add(LK);
        LK.setText("Laki - Laki");
        jPanel2.add(LK, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 164, -1, -1));

        buttonGroup3.add(PR);
        PR.setText("Perempuan");
        jPanel2.add(PR, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 164, -1, -1));

        RT.setText(" ");
        RT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RTActionPerformed(evt);
            }
        });
        jPanel2.add(RT, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 230, 37, -1));

        jLabel15.setText("/");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 233, 10, -1));
        jPanel2.add(RW, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 230, 36, -1));

        STATUS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menikah", "Belum Menikah", "Janda", "Duda", "Pacaran", "Menjalin Hubungan Tanpa Status", "Jalani Aja Dulu", " " }));
        jPanel2.add(STATUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 331, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 0, -1, 504));

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 492, -1, -1));

        jLabel17.setText("BERLAKU ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel29.setText(":");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 10, 10));

        HARI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel2.add(HARI, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));

        BULAN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel2.add(BULAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        TAHUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAHUNActionPerformed(evt);
            }
        });
        jPanel2.add(TAHUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIKActionPerformed

    private void TTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TTLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TTLActionPerformed

    private void CETAKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CETAKActionPerformed
        // TODO add your handling code here:
        
         if(NAMA.getText().length()==0||NIK.getText().length()==0||TTL.getText().length()==0||LK.getText().length()==0||PR.getText().length()==0||ALAMAT.getText().length()==0||RT.getText().length()==0||RW.getText().length()==0||KECAMATAN.getText().length()==0||INA.getText().length()==0||ASING.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Jangan SENDIRI","Harap Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);

        }
        String nama = NAMA.getText();
        String nik = NIK.getText();
        String ttl = TTL.getText();
        
        String JenisKelamin = null;
        if(LK.isSelected())
            JenisKelamin = LK.getText();
        else if (PR.isSelected())
            JenisKelamin = PR.getText();
        
        String alamat = ALAMAT.getText();
        String rt = RT.getText();
        String rw = RW.getText();
        String camat = KECAMATAN.getText();
        String agama = AGAMA.getSelectedItem().toString();
        String status = STATUS.getSelectedItem().toString();
        String kerja = KERJA.getSelectedItem().toString();
        
        String negara = null;
        if(INA.isSelected())
            negara = INA.getText();
        else if (ASING.isSelected())
            negara = ASING.getText();
        
        String hari = HARI.getSelectedItem().toString();
        String bulan = BULAN.getSelectedItem().toString();
        
        double In=Double.parseDouble(TAHUN.getText());
        double Ha;

            Ha=In+5; /*Nda tau cara parsing double ke integer ka jadi ada komanya*/

        
        

        
        Hasil a = new Hasil();
        a.setVisible(true);

        
        
       
        a.out.setText("Nama \t\t\t:" +nama+ "\nNIK \t\t\t:"+nik+"\nTempat Tanggal Lahir \t\t:"+ttl+"\nJenis Kelamin \t\t\t:"+JenisKelamin+"\nAlamat \t\t\t: "+alamat+"\nRT \t\t\t:"+rt+"\nRW \t\t\t:"+rw+"\nKecamatan \t\t\t:"+camat+"\nAgama \t\t\t:"+agama+"\nStatus \t\t\t:"+status+"\nPekerjaan Anda \t\t:"+kerja+"\nKewarganegaraan \t\t:"+negara+
                "\nMasa Berlaku \t\t\t:"+hari+"-"+bulan+"-"+Ha);
    }//GEN-LAST:event_CETAKActionPerformed

    private void KELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KELUARActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_KELUARActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        NAMA.setText("");
        NIK.setText("");
        TTL.setText("");
        LK.setText("");
        PR.setText("");
        ALAMAT.setText("");
        RT.setText("");
        RW.setText("");
        KECAMATAN.setText("");
        INA.setText("");
        ASING.setText("");
        BERLAKU.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void RTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RTActionPerformed

    private void TAHUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAHUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TAHUNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AGAMA;
    private javax.swing.JTextField ALAMAT;
    private javax.swing.JRadioButton ASING;
    private javax.swing.JTextField BERLAKU;
    private javax.swing.JComboBox<String> BULAN;
    public javax.swing.JButton CETAK;
    private javax.swing.JComboBox<String> HARI;
    private javax.swing.JRadioButton INA;
    private javax.swing.JTextField KECAMATAN;
    private javax.swing.JButton KELUAR;
    private javax.swing.JComboBox<String> KERJA;
    private javax.swing.JRadioButton LK;
    private javax.swing.JTextField NAMA;
    private javax.swing.JTextField NIK;
    private javax.swing.JRadioButton PR;
    private javax.swing.JTextField RT;
    private javax.swing.JTextField RW;
    private javax.swing.JComboBox<String> STATUS;
    private javax.swing.JTextField TAHUN;
    private javax.swing.JTextField TTL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
